/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime/$id': typeof AnimeIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime/$id': typeof AnimeIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime/$id': typeof AnimeIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime/$id' | '/groups/' | '/groups/$groupId' | '/profile/' | '/profile/$userId' | '/shared/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime/$id' | '/groups/' | '/groups/$groupId' | '/profile/' | '/profile/$userId' | '/shared/$token'
  id: '__root__' | '/' | '/anime/$id' | '/groups/' | '/groups/$groupId' | '/profile/' | '/profile/$userId' | '/shared/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeIdRoute: typeof AnimeIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeIdRoute: AnimeIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
